
Generated 5 folds for cross-validation on 30577 labeled nodes.
Using device: mps

============================================================
üèõÔ∏è  Stage 1: Optuna Search for Best Architecture (fixed LR)
Using fixed Learning Rate: 0.005
============================================================
[W 2025-06-16 18:03:14,939] Trial 0 failed with parameters: {'l2_reg': 0.00014981928309445043, 'n_channels': 64, 'n_gnn_layers': 7, 'dropout_rate': 0.24918568610275313, 'gradient_clipping': 0.1855056401469255, 'edge_gate_hidden_dim': 32, 'n_channels_preproc': 16} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/Users/fabiocolantonio/plASgraph2_pyg/.venv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/Users/fabiocolantonio/plASgraph2_pyg/model/../src/plASgraph2_train.py", line 170, in <lambda>
    study.optimize(lambda trial: objective(trial, parameters, data, device, splits, labeled_indices),
  File "/Users/fabiocolantonio/plASgraph2_pyg/model/../src/plASgraph2_train.py", line 94, in objective
    val_outputs = model(data)
  File "/Users/fabiocolantonio/plASgraph2_pyg/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/fabiocolantonio/plASgraph2_pyg/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/fabiocolantonio/plASgraph2_pyg/src/architecture.py", line 216, in forward
    h = self.ggnn_layer(h, edge_index, edge_attr=current_edge_attr)
  File "/Users/fabiocolantonio/plASgraph2_pyg/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/fabiocolantonio/plASgraph2_pyg/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/fabiocolantonio/plASgraph2_pyg/src/architecture.py", line 128, in forward
    return self.propagate(edge_index_with_self_loops, x=x, norm=norm, edge_attr=edge_attr_with_self_loops)
  File "/var/folders/gl/_h4nt3w10cs0cymjs5g3dknr0000gn/T/architecture_GGNNConv_propagate_ptno2ef7.py", line 142, in propagate
    def propagate(
KeyboardInterrupt
[W 2025-06-16 18:03:14,944] Trial 0 failed with value None.
